### ISSUE TITLE
Improve marks/arrows/tips

### ISSUE THREAD

**Issue by fenjalien** [johannes-wolf/cetz#210]
The ability to customise marks and how they are handeld are currently very limited. Cetz only has a `size` parameter and five types. While tikz has many more configuration options and tips (https://tikz.dev/tikz-arrows). I think we should improve the current marks to match (within reason) tikz's features.

**Comment by johannes-wolf** [comment]
What should be improved? There is already PR #164 for improving the mark placement.
We _could_ allow setting multiple marks for lines but that is already possible by using `place-marks`.

**Comment by fenjalien** [comment]
> What should be improved? There is already PR #164 for improving the mark placement. We _could_ allow setting multiple marks for lines but that is already possible by using `place-marks`.

Note my orignal comment has been edited

**Comment by johannes-wolf** [comment]
Currently we have:
- size
- stroke
- fill

What could be added:
- length (as in length _on_ the line, from tip to stem)
- angle (added with #164)
- offset (to offset marks from their original position along the paths-segmenth they are placed on)

With PR #164, `angle` gets added for triangular marks.
I think cetz would benefit from a nicer arrow mark (like the tikz one), that uses beziers instead of straight lines.

**Comment by johannes-wolf** [comment]
Closing in favor of #331.
