### ISSUE TITLE
chart: Make ticks more configurable

### ISSUE THREAD

**Issue by johannes-wolf** [johannes-wolf/cetz#263]
Provide options for:
- `-format`
- `-decimals`

**Comment by dscso** [comment]
https://github.com/johannes-wolf/cetz/blob/0.2.0/src/lib/axes.typ#L232
I'd personally think removing some base numbers would be a good idea as e.g. 1.5 is not a really intuitive multiple... I think sticking to 1, 2, (maybe 3), 5, 10 would be more intuitive for reading charts.

Maybe this is also due to my lacking knowledge of the Einmaleins 😂

**Comment by johannes-wolf** [comment]
We can make this configurable, yes.
