### ISSUE TITLE
Version inconsistencies

### ISSUE THREAD

**Issue by genericusername3** [johannes-wolf/cetz#349]
~~Hi, it seems that [the package in `typst/packages`](https://github.com/typst/packages/blob/main/packages/preview/cetz/0.1.2) isn't actually version 0.1.2, as it's missing the `*-min` parameters to `chart.barchart` and `chart.columnchart` functions, for instance, which were introduced in [(Github tag) 0.1.2](https://github.com/johannes-wolf/cetz/releases/tag/v0.1.2).~~

~~Could you update version 0.1.2 in `typst/packages` so that it's actually 0.1.2?~~

---

The [manual for 0.1.2](https://raw.githubusercontent.com/johannes-wolf/cetz/v0.1.2/manual.pdf) (and [current manual](https://raw.githubusercontent.com/johannes-wolf/cetz/master/manual.pdf)) also claims it's version 0.1.1. This is a minor thing, I imagine some file just didn't get updated.

**Comment by matthew-e-brown** [comment]
Are you sure there's a mismatch? The only difference I can see is that `lib.typ` has the wrong version in the main repo ([which was caught when 0.1.2 was published](https://github.com/typst/packages/pull/165#discussion_r1342000965)).

![All files are identical except for lib.typ, which has is different on only a single line.](https://github.com/johannes-wolf/cetz/assets/43387454/779f11e5-cbb8-4b3a-be2a-c2409d9ede0e)

CeTZ v0.1.2 [was released on September 30th](https://github.com/typst/packages/pull/165#event-10519202557). Looking at [the blame for `chart.typ`](https://github.com/johannes-wolf/cetz/blame/master/src/lib/chart.typ#L113-L114), the `*-min` parameters you're looking for weren't added until commit b8f546c on October 7th.

Those updates haven't been released yet. 😄

**Comment by matthew-e-brown** [comment]
I have definitely been caught off guard by the manual's version number before, too. 😄 Perhaps the URL in the readme that says to "see the manual" could be made to point at the latest _released_ version, instead of the one currently on `master`.

Although... I'm not sure if the manual's PDF even needs to be in the repo, does it? It's not really code. Maybe it should actually just be an attachment on each release (which would be included when publishing to `typst/packages`)... then the link in the readme could point to `/releases/latest/download/manual.pdf`.

**Comment by johannes-wolf** [comment]
The link in the README now points to the manual on a tag called `stable` that should be set to the latest release and is currently on 0.1.2. The wrong version number in the manual is bad, but I don't want to fix that yet.
